# Generated by Django 6.0.1 on 2026-02-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('Product_name', models.CharField(max_length=100, unique=True)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField()),
                ('ProductImage', models.ImageField(upload_to='products')),
            ],
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='CategoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
    ]
