# Generated by Django 6.0.2 on 2026-03-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_productdb_alter_categorydb_categoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Icon', models.CharField(blank=True, help_text='Font Awesome icon class e.g. fa-truck', max_length=100, null=True)),
                ('ServiceImage', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
    ]
