# Generated by Django 6.0.1 on 2026-02-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_registrationdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdb',
            old_name='password2',
            new_name='password1',
        ),
    ]
